### ISSUE TITLE
The values in the "liveCameraPoseEstimation.py " file are going as NaN or Inf.

### ISSUE THREAD

**Issue by serkanMzlm** [niconielsen32/ComputerVision#31]
I calibrated the camera and when I run it, it gives certain values for a while and then writes NaN, the program throws an error.
```
/usr/lib/python3/dist-packages/numpy/linalg/linalg.py:2561: RuntimeWarning: overflow encountered in reduce
  return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
Traceback (most recent call last):
  File "liveCameraPoseEstimation.py", line 369, in <module>
    pc.plot_camera(ax, vo.K, camera_pose_poses[i],
  File "/home/.local/lib/python3.10/site-packages/pytransform3d/camera.py", line 266, in plot_camera
    cam2world = check_transform(cam2world, strict_check=strict_check)
  File "/home/.local/lib/python3.10/site-packages/pytransform3d/transformations/_utils.py", line 35, in check_transform
    check_matrix(A2B[:3, :3], strict_check=strict_check)
  File "/home/.local/lib/python3.10/site-packages/pytransform3d/rotations/_utils.py", line 476, in check_matrix
    raise ValueError(error_msg)
ValueError: Expected rotation matrix, but it failed the test for inversion by transposition. np.dot(R, R.T) gives array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])
```

**Comment by Ncouch64** [comment]
I am also encountering this problem, @serkanMzlm were you able to solve the problem?
